config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :rolodexes

end

app/models/rolodex.rb
class Rolodex < ActiveRecord::Base
  validates :name, presence: true, length: {minimum: 5 }
  validates :address, presence: true

  def display_address
    addresses = "#{address} "
    if address_2
      addresses << "<br>#{address_2}"
    end
    "#{addresses}<br>
    #{city}, #{state} #{zip}"
  end

  US_STATES = [ "Alaska",
                "Alabama",
                "Arkansas",
                "American Samoa",
                "Arizona",
                "California",
                "Colorado",
                "Connecticut",
                "District of Columbia",
                "Delaware",
                "Florida",
                "Georgia",
                "Guam",
                "Hawaii",
                "Iowa",
                "Idaho",
                "Illinois",
                "Indiana",
                "Kansas",
                "Kentucky",
                "Louisiana",
                "Massachusetts",
                "Maryland",
                "Maine",
                "Michigan",
                "Minnesota",
                "Missouri",
                "Mississippi",
                "Montana",
                "North Carolina",
                "North Dakota",
                "Nebraska",
                "New Hampshire",
                "New Jersey",
                "New Mexico",
                "Nevada",
                "New York",
                "Ohio",
                "Oklahoma",
                "Oregon",
                "Pennsylvania",
                "Puerto Rico",
                "Rhode Island",
                "South Carolina",
                "South Dakota",
                "Tennessee",
                "Texas",
                "Utah",
                "Virginia",
                "Virgin Islands",
                "Vermont",
                "Washington",
                "Wisconsin",
                "West Virginia",
                "Wyoming"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @rolodexes = Rolodex.all
  end
end

app/controllers/rolodexes_controller.rb
class RolodexesController < ApplicationController
  # This method will be called by each action
  before_filter :find_rolodex, only: [:show, :edit, :update, :destroy]

  def show
  end
  
  def new
    @rolodex = Rolodex.new
  end

  def create
    @rolodex = Rolodex.new rolodex_params
    if @rolodex.save
      # display a success message to the user
      flash[:notice] = "You successfully saved this contact!"
      redirect_to root_path
    else
      flash[:error] = "You were unsuccessful saving this contact!"
      # display an error message to the user
      render :new
    end
    
  end

  def edit
  end

  def update
    if @rolodex.update_attributes rolodex_params
      # display a success message to the user
      flash[:notice] = "You successfully updated this contact!"
      redirect_to root_path
    else
      flash[:error] = "You were unsuccessful updating this contact!"
      # display an error message to the user
      render :edit
    end
  end

  def destroy
    @rolodex.delete
    redirect_to root_path 
  end

  private
    def rolodex_params
      params.require(:rolodex).permit(:name, :phone_number, :email, :address, :address_2, :city, :state, :zip, :is_cool, :gender, :description)
    end

    def find_rolodex
      @rolodex = Rolodex.find params[:id]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rolodexes_helper.rb
module RolodexesHelper
end

app/views/home/index.html.erb
<h1>Hey man</h1>

<%=link_to 'Create Contact',  new_rolodex_path %>
<br>

<% @rolodexes.each do |rolodex| %>
  <%= link_to "#{rolodex.name}", rolodex_path(rolodex) %>
  <!-- <a href="/rolodexes/<%= rolodex.id%>"> Look at this link</a> -->
  <%= link_to 'Edit', edit_rolodex_path(rolodex) %>
  |
  <%= link_to 'Delete', rolodex_path(rolodex), method: :destroy %>
  <br>
<% end %>

app/views/layouts/_error_messages.html.erb
<!-- <%= object.errors.messages %> -->
<% object.errors.messages.each do |k, v| %>
  <% v.each do |message| %>
    <%= k.capitalize %>
    <%= message %>
    <br>
  <% end %>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% elsif flash[:error] %>
  <div class="error"><%= flash[:error] %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Class13</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/flash' %>

  <%= yield %>

</body>
</html>

app/views/rolodexes/_form.html.erb
<%= form_for @rolodex do |f| %>
  <%= render 'layouts/error_messages', object: @rolodex %>
  <br>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>

  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>
  <br>

  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>

  <%= f.label :address %>
  <%= f.text_field :address %>
  <br>

  <%= f.label :address_2 %>
  <%= f.text_field :address_2 %>
  <br>

  <%= f.label :city %>
  <%= f.text_field :city %>
  <br>

  <%= f.label :state %>
  <%= f.select :state, options_for_select(Rolodex::US_STATES), include_blank: '--- Select ---' %>
  <br>

  <!-- <select>
    <option>Alaska</option>
    <option>Delaware</option>
    <option>Pennsylvania</option>
  </select> -->

  <%= f.label :zip %>
  <%= f.text_field :zip %>
  <br>

  <%= f.label :is_cool %>
  <%= f.label :is_cool, "Yes", value: true %>
  <%= f.radio_button :is_cool, true %>
  <%= f.label :is_cool, "No", value: false %>
  <%= f.radio_button :is_cool, false %>
  <br>

  <%= f.label :gender %>
  <%= f.label :gender, "Male", value: "male" %>
  <%= f.radio_button :gender, "male" %>
  
  <%= f.label :gender, "Female", value: "female" %>
  <%= f.radio_button :gender, "female" %>
  <br>

  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>

  <%= f.submit %>
<% end %>
<%= link_to 'Home', root_path %>

app/views/rolodexes/edit.html.erb
<h1>Edit Rolodex: <%= @rolodex.name %></h1>

<%= render 'form' %>
<!-- Go look for _form in this folder. -->

app/views/rolodexes/new.html.erb
<h1>New Rolodex</h1>

<%= render 'form' %>
<!-- Go look for _form in this folder. -->

app/views/rolodexes/show.html.erb
<h1>Showing <%= @rolodex.name %></h1>
<hr>
<%= @rolodex.phone_number %>
<br>
<%= @rolodex.email %>
<br>
<%= @rolodex.display_address.html_safe %>
<br>
Is this guy cool? <%= @rolodex.is_cool %>
<br>
<%= @rolodex.gender.try(:capitalize) %>
<br>
<%= @rolodex.description %>
<br>
<%= link_to 'Home', root_path %><br>